# Generated by Django 5.2 on 2025-05-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='posts/')),
                ('paragraph', models.TextField(max_length=2000)),
            ],
        ),
    ]
